FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json .
RUN npm install --force

ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

COPY . .
CMD ["npm", "start"]

# docker run \
#       --rm -d -p 3000:3000 \
#       -v ./public:/app/public
#       -v ./src:/app/src \
#       react-app:dev